In [1]:
import pandas as pd
import os
import sqlalchemy
import pyodbc
from datetime import datetime, timedelta
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn import tree
import sklearn
from imblearn.over_sampling import SMOTE
from forex_python.converter import CurrencyRates
from time import sleep

In [2]:
# libraries = ['pd', 'sqlalchemy', 'pyodbc', 'np', 'sklearn', 'imblearn']
# def get_version(lib):
#     lib = eval(lib)
#     try:
#         return lib.__version__
#     except AttributeError:
#         return "not found"
    
# for lib in libraries:
#     version = get_version(lib)
#     print(f"{lib}=={version}")

# Объединяем все Excel файлы в 1 датасет

In [3]:
# Имена папок
folders = ["2020.12","2021.01","2021.02","2021.03","2021.04","2021.05",
           "2021.06","2021.07","2021.08","2021.09","2021.10","2021.11","2021.12","2022.01"]

In [5]:
# Пустой список путей + даты
file_paths = []
# Для каждой папки из списка папок
for folder in folders:
    # Лепим путь к файлу
    folder_path = os.path.join(r"C:\Users\MikheevMN\Эшелоны", folder)
    # Достаем какие файлы в папке
    files = os.listdir(folder_path)
    # Для файла из папки
    for file in files:
        # Если файл не временный то добавляем путь в список путей с датой в конце
        if not file.startswith('~$'):
            file_paths.append((os.path.join(folder_path, file), folder))
            
for file in file_paths:
    print(file)

('C:\\Users\\MikheevMN\\Эшелоны\\2020.12\\Портфель цб 12 2020 + об_эшелон.xlsx', '2020.12')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.01\\Портфель цб 01 21.xlsm', '2021.01')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.02\\Портфель цб 02 21 копия.xlsm', '2021.02')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.03\\Портфель цб 03 21 к.xlsm', '2021.03')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.04\\Копия Портфель цб 04 21-2.xlsm', '2021.04')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.05\\Портфель цб 05 21.xlsm', '2021.05')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.06\\Портфель цб 06 21.xlsm', '2021.06')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.07\\Портфель цб 07 21.xlsm', '2021.07')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.08\\Портфель цб 08 21.xlsm', '2021.08')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.09\\Портфель цб 09 21.xlsm', '2021.09')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.10\\Портфель цб 10 21.xlsm', '2021.10')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.11\\Портфель цб 11 21.xlsm', '2021.11')
('C:\\Users\\MikheevMN\\Эшелоны\\2021.12\\Портфель цб 12 21.xlsm', '2021.12')
('C:\\Users\\MikheevMN\\Эшелоны\\2022.01\\Портфель цб 01 22.xlsm', '2022.01')

In [4]:
# Пустой датасет для хранения
combined_data = pd.DataFrame()

In [5]:
column_names = ["Index", "Description", "Duration", "Amount", "Currency", "TRPS", "Rating", "Echelon"]
# Для пути и даты в списке
for file_path, folder in file_paths:
    excel_data = pd.read_excel(file_path, sheet_name="Эшелоны результат", usecols="A:H", header=None)
    excel_data.columns = column_names
    excel_data["Date"] = folder
    combined_data = combined_data.append(excel_data, ignore_index=True)
combined_data

,Index,Description,Duration,Amount,Currency,TRPS,Rating,Echelon,Date
0,ISIN,Description,Дюрация,Amount Outstanding,Currency,TRPS Score,Рейтинг Буква,Eshelon,2020.12
1,XS2134628069,MMCFN 2.550 09/11/25 '25,4.223,500000000,USD,10,BBB-,1,2020.12
2,XS1449458915,GOTRL 5.950 07/19/21,0.558,350000000,USD,10,BB,2,2020.12
3,XS1319822752,EVRE 8.250 01/28/21,0.097,750000000,USD,10,BB+,1,2020.12
4,XS1433454243,FASPM 5.375 06/16/23,2.358,900000000,USD,10,BB,2,2020.12
5,CH0385518086,AFHDS 2.875 11/09/22,1.85,165000000,CHF,9,BB-,2,2020.12
6,XS1951067039,CBOMF 5.150 02/20/24,2.89,327228000,EUR,10,BB-,2,2020.12
7,XS1759468967,UNCRS 4.850 02/01/23,1.991,500000000,USD,8,B+,2,2020.12
8,XS1400710726,VON 7.250 04/26/23 '23,1.964,700000000,USD,10,BB,2,2020.12
9,XS1772800204,DMAIR 5.075 02/15/23 '22,1.798,300000000,USD,10,BB,2,2020.12
10,XS2010044548,CPPFD 4.500 09/19/24 '24,3.237,300000000,USD,9,BB-,2,2020.12
11,XS2010044381,GTEPT 4.949 02/18/26,4.555,550000000,USD,10,BB,2,2020.12
12,XS2060792236,KAPIA 4.125 10/09/24 '24,3.316,400000000,USD,9,BB,2,2020.12
13,XS2058691663,VON 4.000 04/09/25 '25,3.755,1000000000,USD,10,BB,2,2020.12
14,XS2010040397,UKFIN 4.000 10/22/24,3.575,500000000,USD,9,BB-,2,2020.12
15,XS2063279959,ALFAB 5.950 04/15/30 '25 FRN,3.839,850000000,USD,10,BB-,2,2020.12
16,XS2099763075,CBOMF 4.700 01/29/25,3.719,541000000,USD,10,BB-,2,2020.12
17,XS2124187571,GAZFI 3.250 02/25/30 MTN,7.949,2000000000,USD,10,BBB,1,2020.12
18,XS2157526315,GAZFI 2.950 04/15/25 MTN,4.043,1000000000,EUR,10,BBB,1,2020.12
19,XS2243631095,GAZFI 4.598 Perp '25 FRN,4.377,1400000000,USD,9,BB+,1,2020.12
20,XS2159874002,LKOH 3.875 05/06/30,7.977,1500000000,USD,10,BBB,1,2020.12
21,XS0841671000,SGEEL 5.900 10/17/22 MTN,1.736,634051000,USD,10,BBB,1,2020.12
22,XS0800817073,VEFNC 6.025 07/05/22,1.452,1000000000,USD,10,BBB-,1,2020.12
23,XS0830192711,STGPN 4.375 09/19/22 MTN,1.678,1500000000,USD,10,BBB,1,2020.12
24,XS2183144810,AFHDS 2.700 06/11/23 MTN,2.388,350000000,EUR,9,BB-,2,2020.12
25,XS0861981180,ROSNI 4.199 03/06/22 MTN,1.173,2000000000,USD,10,BBB-,1,2020.12
26,XS1622146758,MMCFN 3.849 04/08/22,1.264,500000000,USD,10,BBB-,1,2020.12
27,XS1567051443,SGEEL 3.850 08/27/21,0.668,500000000,USD,10,BBB,1,2020.12
28,XS2010030919,ALRSX 3.100 06/25/27,5.864,500000000,USD,10,BBB-,1,2020.12
29,XS1038646078,GAZCA 3.600 02/26/21 MTN,0.178,750000000,EUR,10,BBB,1,2020.12
...,...,...,...,...,...,...,...,...,...
2064,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2065,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2066,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2067,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2068,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2069,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2070,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2071,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2072,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2073,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2074,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2075,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2076,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2077,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2078,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2079,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2080,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2081,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2082,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2083,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2084,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2085,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2086,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2087,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2088,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2089,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2090,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2091,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2092,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01
2093,0,GRUPP 06/27/21,Internal error,0,RUB,NaN,NaN,"Ошибка, не численные значения",2022.01

In [6]:
# Выбираем только те строки, где столбец Эшелон != Ошибка, не численные значения
combined_data = combined_data[~combined_data["Echelon"].astype(str).str.contains("Ошибка, не численные значения")]

In [7]:
# Убираем дубликаты строк(при отборе исключаем Date)
combined_data.drop_duplicates(subset=combined_data.columns.difference(["Date"]), inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
# Убираем строки с Null
combined_data.dropna(inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [9]:
# Преобразуем Date в datetime
combined_data["Date"] = pd.to_datetime(combined_data["Date"], format='%Y.%m')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [10]:
# Удаляем текстовые TRPS данные
combined_data['TRPS'] = pd.to_numeric(combined_data['TRPS'], errors='coerce')
combined_data.dropna(subset=['TRPS'], inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
# Меняем тип данных и обновляем индексы
combined_data['Duration'] = combined_data['Duration'].astype(float)
combined_data['Amount'] = combined_data['Amount'].astype(float)
combined_data['Echelon'] = combined_data['Echelon'].astype(int)
combined_data.reset_index(drop=True, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [12]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 9 columns):
Index          988 non-null object
Description    988 non-null object
Duration       988 non-null float64
Amount         988 non-null float64
Currency       988 non-null object
TRPS           988 non-null float64
Rating         988 non-null object
Echelon        988 non-null int32
Date           988 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int32(1), object(4)
memory usage: 65.7+ KB

In [13]:
# Букавы рейтинг меняем на машина понимать язык
replacement_dict = {
    'B-': 1,
    'B': 2,
    'B+': 3,
    'BB-': 4,
    'BB': 5,
    'BB+': 6,
    'BBB-': 7,
    'BBB': 8,
    'BBB+': 9,
    'A-': 10
}
combined_data['Rating'] = combined_data['Rating'].replace(replacement_dict)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [14]:
set(combined_data['Rating'])

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [15]:
# combined_data.to_csv('echelons.csv', index=False)

In [16]:
# combined_data = pd.read_csv('echelons.csv')
# combined_data["Date"] = pd.to_datetime(combined_data["Date"])
# combined_data.head()

,Index,Description,Duration,Amount,Currency,TRPS,Rating,Echelon,Date
0,XS2134628069,MMCFN 2.550 09/11/25 '25,4.223,500000000.0,USD,10.0,7,1,2020-12-01
1,XS1449458915,GOTRL 5.950 07/19/21,0.558,350000000.0,USD,10.0,5,2,2020-12-01
2,XS1319822752,EVRE 8.250 01/28/21,0.097,750000000.0,USD,10.0,6,1,2020-12-01
3,XS1433454243,FASPM 5.375 06/16/23,2.358,900000000.0,USD,10.0,5,2,2020-12-01
4,CH0385518086,AFHDS 2.875 11/09/22,1.850,165000000.0,CHF,9.0,4,2,2020-12-01

In [17]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 9 columns):
Index          988 non-null object
Description    988 non-null object
Duration       988 non-null float64
Amount         988 non-null float64
Currency       988 non-null object
TRPS           988 non-null float64
Rating         988 non-null int64
Echelon        988 non-null int64
Date           988 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(2), object(3)
memory usage: 69.5+ KB

# Достаем из БД уровень листинга бумаги

In [135]:
def query_db(securityid, date):
    arr = 0
    connection_string = r'Driver={SQL Server};Server=DEVELOPERS-SQL;Database=InnerData;Trusted_Connection=yes'
    connection = pyodbc.connect(connection_string)
    cursor = connection.cursor()
    
    interval_start = date - timedelta(days=100)
                                      
    # тут важно!!! пендосский формат год/день/месяц
    date = date.strftime("%Y-%d-%m")
    interval_start = interval_start.strftime("%Y-%d-%m")
    
    query = f"""
    SELECT TOP 1 ListName
    FROM MM00001_SEM21
    WHERE SecurityId = CONVERT(VARCHAR, ?) AND TradeDate >= ? AND TradeDate < ?
    ORDER BY TradeDate DESC
    """
    
    cursor.execute(query, (securityid, interval_start, date))
    
    arr = cursor.fetchall()
    
    cursor.close()
    connection.close()
    return arr

In [142]:
new_column = []
for index, row in combined_data.iterrows():
    list_name = query_db(row['Index'], row['Date'])
    new_column.append(list_name)

In [182]:
new_column[:5]

[[(3, )], [(3, )], [(-1, )], [(3, )], []]

In [183]:
new_column_flat = []
for sublist in new_column:
    if sublist == []:
        new_column_flat.append(None)
    else:
        for item in sublist:
            new_column_flat.append(item[0])           
new_column_flat[:5]

[3, 3, -1, 3, None]

In [181]:
len(new_column_flat)

988

In [184]:
combined_data['Listing'] = new_column_flat

In [192]:
combined_data = combined_data.dropna()
combined_data = combined_data.reset_index(drop=True)

# Ломбардный список

In [3]:
import xml.etree.ElementTree as ET

In [51]:
folder = ["2020-12-01","2021-01-01","2021-02-01","2021-03-01","2021-04-01","2021-05-01",
           "2021-06-01","2021-07-01","2021-08-01","2021-09-01","2021-10-01","2021-11-01","2021-12-01","2022-01-01"]

In [91]:
# XML
combined_data["Lombard"] = False
# Для каждого файла из папки
for file in folder:
    # Лепим путь к файлу
    file_path = os.path.join(r"C:\Users\MikheevMN\lombard_xml", file)
    file_path = file_path + ".xml"
    tree = ET.parse(file_path)
    tree = ET.parse(xml_path)
    root = tree.getroot()
    # Список исинов
    isin_list = []
    for emitent in root.findall("./Papers/Emitent"):
        for paper in emitent.findall("Paper"):
            isin = paper.get("ISIN")
            mask = (combined_data['Date'] == file) & (combined_data['Index'] == isin)
            if mask.any():
                combined_data.loc[mask, 'Lombard'] = True

In [89]:
# OFZ
ofz_xlsx = r"C:\Users\MikheevMN\bondsearch_26_04_2024.xlsx"
xlsx_data = pd.read_excel(ofz_xlsx, usecols=[18])
for index, row in xlsx_data.iterrows():
    mask = combined_data['Index'] == row['ISIN']
    if mask.any():
        combined_data.loc[mask, 'Lombard'] = True

In [92]:
combined_data['Lombard'] = combined_data['Lombard'].replace({True: 1, False: 0})

In [96]:
# combined_data.to_csv('echelons.csv', index=False)

# Ликвидность

## Создал таблицу в бд с курсами валют для разных дат

In [19]:
# df_ex_rate = pd.read_excel(r'C:\Users\MikheevMN\indexes_archive_20240427.xlsx')
# df_ex_rate["Дата"] = pd.to_datetime(df_ex_rate["Дата"], format="%d.%m.%Y")

In [36]:
# df_ex_rate['RUR'] = 1
# df_ex_rate_melted = pd.melt(df_ex_rate, id_vars=['Дата'], var_name='Валюта', value_name='Курс')
# df_ex_rate_melted['Валюта'] = df_ex_rate_melted['Валюта'].apply(lambda x: 'USD' if x == 'USD/RUB (FX)' else 'EUR' if x == 'EUR/RUB (FX)' else 'RUR')
# df_ex_rate_melted.at[966, 'Курс'] = 87.77
# df_ex_rate_melted[df_ex_rate_melted['Дата']=='2021-07-21']

           Дата Валюта   Курс
385  2021-07-21    USD  73.87
966  2021-07-21    EUR  87.77
1547 2021-07-21    RUR   1.00

In [37]:
# # пробую через алхими
# connection_string = r'Driver={SQL Server};Server=DEVELOPERS-SQL;Database=InnerData;Trusted_Connection=yes'
# params = urllib.parse.quote_plus(connection_string)
# engine = sqlalchemy.create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)

# table_name = 'Exchange_rate'
# df_ex_rate_melted.to_sql(table_name, engine, if_exists='replace', index=False)

## Vi сделано

In [50]:
# В одну дату может быть 2 записи: в валюте и в рублях

In [10]:
def query_db_vi(securityid, date):
    arr = 0
    connection_string = r'Driver={SQL Server};Server=DEVELOPERS-SQL;Database=InnerData;Trusted_Connection=yes'
    connection = pyodbc.connect(connection_string)
    cursor = connection.cursor()
    
    interval_start = date - timedelta(days=300)
                                      
    # тут важно!!! американский формат год/день/месяц
    date = date.strftime("%Y-%d-%m")
    interval_start = interval_start.strftime("%Y-%d-%m")
    
    query = f"""
    SELECT ROUND(AVG(AmountInDay), 1)
    FROM(
        SELECT TOP 30 TradeDate, SUM(Amount) AS AmountInDay
        FROM(
            SELECT DISTINCT TradeDate, CurrencyId, Value * Курс AS Amount
            FROM MM00001_SEM21 sem LEFT JOIN Exchange_rate ex
                ON ex.Валюта = sem.CurrencyId AND ex.Дата = sem.TradeDate
            WHERE SecurityId = CONVERT(VARCHAR, ?) AND TradeDate >= ? AND TradeDate < ? AND (BoardId = 'TQCB' OR BoardId = 'TQOD' OR BoardId = 'TQOE' OR BoardId = 'TQOY')
            ) AS subquery
        GROUP BY TradeDate
        ORDER BY TradeDate DESC) AS subquery2
    """
    
    cursor.execute(query, (securityid, interval_start, date))
    
    arr = cursor.fetchall()
    
    cursor.close()
    connection.close()
    return arr

In [11]:
query_db_vi('XS2134628069', combined_data['Date'][1])

[(105811.5, )]

## Рассчет V

In [12]:
# пока что удалил дату начала, просто беру топ 30
def query_db_v(date):
    arr = 0
    connection_string = r'Driver={SQL Server};Server=DEVELOPERS-SQL;Database=InnerData;Trusted_Connection=yes'
    connection = pyodbc.connect(connection_string)
    cursor = connection.cursor()
    
    interval_start = date - timedelta(days=150)
                                      
    # тут важно!!! ПОЧЕМУ ТО ТЕПЕРЬ РАБОТАЕТ гггг.мм.дд UPD опять ддмм
    date = date.strftime("%Y-%d-%m")
    interval_start = interval_start.strftime("%Y-%d-%m")
    
    query = f"""
    SELECT ROUND(AVG(AmountDay), 0)
    FROM(
        SELECT TOP 30 TradeDate, SUM(Amount) AS AmountDay
        FROM(
            SELECT DISTINCT TradeDate, CurrencyId, SecurityId, Value * Курс AS Amount
            FROM MM00001_SEM21 sem LEFT JOIN Exchange_rate ex
                 ON ex.Валюта = sem.CurrencyId AND ex.Дата = sem.TradeDate
            WHERE TradeDate >= ? AND TradeDate < ? AND EngType = 'bn' AND (BoardId = 'TQCB' OR BoardId = 'TQOD' OR BoardId = 'TQOE' OR BoardId = 'TQOY')
            ) AS subquery
        GROUP BY TradeDate
        ORDER BY TradeDate DESC) AS subquery2
    """
    
    cursor.execute(query, (interval_start, date))
    
    arr = cursor.fetchall()
    
    cursor.close()
    connection.close()
    return arr

In [13]:
query_db_v(combined_data['Date'][1])

[(4770814893.0, )]

## Рассчет NTi

In [14]:
def query_db_nti(securityid, date):
    arr = 0
    connection_string = r'Driver={SQL Server};Server=DEVELOPERS-SQL;Database=InnerData;Trusted_Connection=yes'
    connection = pyodbc.connect(connection_string)
    cursor = connection.cursor()
    
    interval_start = date - timedelta(days=300)
                                      
    # тут важно!!! американский формат год/день/месяц
    date = date.strftime("%Y-%d-%m")
    interval_start = interval_start.strftime("%Y-%d-%m")
    
    query = f"""
    SELECT ROUND(AVG(convert(float, TradesInDay)), 3)
    FROM(
        SELECT TOP 30 TradeDate, SUM(NumTrades) AS TradesInDay
        FROM(
            SELECT DISTINCT TradeDate, Value, NumTrades
            FROM MM00001_SEM21
            WHERE SecurityId = CONVERT(VARCHAR, ?) AND TradeDate >= ? AND TradeDate < ? AND (BoardId = 'TQCB' OR BoardId = 'TQOD' OR BoardId = 'TQOE' OR BoardId = 'TQOY')
            ) AS subquery
        GROUP BY TradeDate
        ORDER BY TradeDate DESC) AS subquery2
    """
    
    cursor.execute(query, (securityid, interval_start, date))
    
    arr = cursor.fetchall()
    
    cursor.close()
    connection.close()
    return arr

In [15]:
query_db_nti('XS1449458915', combined_data['Date'][1])

[(0.567, )]

## Рассчет NT

In [16]:
# пока что удалил дату начала, просто беру топ 30
def query_db_nt(date):
    arr = 0
    connection_string = r'Driver={SQL Server};Server=DEVELOPERS-SQL;Database=InnerData;Trusted_Connection=yes'
    connection = pyodbc.connect(connection_string)
    cursor = connection.cursor()
    
    interval_start = date - timedelta(days=150)
                                      
    # тут важно!!! ПОЧЕМУ ТО ТЕПЕРЬ РАБОТАЕТ гггг.мм.дд UPD опять ддмм
    date = date.strftime("%Y-%d-%m")
    interval_start = interval_start.strftime("%Y-%d-%m")
    
    query = f"""
    SELECT AVG(TradesInDay)
    FROM(
        SELECT TOP 30 TradeDate, SUM(NumTrades) AS TradesInDay
        FROM(
            SELECT DISTINCT TradeDate, CurrencyId, SecurityId, Value, NumTrades
            FROM MM00001_SEM21
            WHERE TradeDate >= ? AND TradeDate < ? AND EngType = 'bn' AND (BoardId = 'TQCB' OR BoardId = 'TQOD' OR BoardId = 'TQOE' OR BoardId = 'TQOY')
            ) AS subquery
        GROUP BY TradeDate
        ORDER BY TradeDate DESC) AS suquery2
    """
    
    cursor.execute(query, (interval_start, date))
    
    arr = cursor.fetchall()
    
    cursor.close()
    connection.close()
    return arr

In [17]:
query_db_nt(combined_data['Date'][1])

[(32507, )]

## Соединяем все

In [38]:
# df = pd.DataFrame(li_base_list_nach)
# df.to_csv('li_base.csv')

In [4]:
li_base = pd.read_csv('li_base.csv')
li_base_list_nach = li_base['0'].tolist()

FileNotFoundError: [Errno 2] No such file or directory: 'li_base.csv'

In [18]:
li_base_column = []
for index, row in combined_data[715:].iterrows():
    # константы
    a = 0.03
    b = 0.07
    # все переменные, идут запросы к бд
    v_i = query_db_vi(row['Index'], row['Date'])[0][0]
    v = query_db_v(row['Date'])[0][0]
    nt_i = query_db_vi(row['Index'], row['Date'])[0][0]
    nt = query_db_v(row['Date'])[0][0]
    
    # формула
    if v_i == None or v == None or nt_i == None or nt == None:
        li_base = None
    else: 
        li_base = pow(v_i/v, a) * pow(nt_i/nt, b)
    li_base_column.append(li_base)

In [39]:
len(li_base_list_nach)

880

In [40]:
combined_data['Liquidity'] = li_base_list_nach
combined_data = combined_data.fillna(0)
combined_data.head()

,Index,Description,Duration,Amount,Currency,TRPS,Rating,Echelon,Date,Listing,Lombard,Liquidity
0,XS2134628069,MMCFN 2.550 09/11/25 '25,4.223,500000000.0,USD,10.0,7,1,2020-12-01,3.0,0,0.342448
1,XS1449458915,GOTRL 5.950 07/19/21,0.558,350000000.0,USD,10.0,5,2,2020-12-01,3.0,1,0.435783
2,XS1319822752,EVRE 8.250 01/28/21,0.097,750000000.0,USD,10.0,6,1,2020-12-01,-1.0,0,0.000000
3,XS1433454243,FASPM 5.375 06/16/23,2.358,900000000.0,USD,10.0,5,2,2020-12-01,3.0,0,0.428966
4,XS1951067039,CBOMF 5.150 02/20/24,2.890,327228000.0,EUR,10.0,4,2,2020-12-01,3.0,0,0.439385

In [ ]:
dummies = pd.get_dummies(combined_data['Currency'])
combined_data = pd.concat([combined_data, dummies], axis=1)
combined_data.drop(columns=['Currency'], inplace=True)

# Можно просто прочитать датасет с этого момента

Было принято решение убрать столбцы с валютой и ломбардный список

In [98]:
# combined_data.to_csv('echelons.csv', index=False)
combined_data = pd.read_csv('echelons.csv')
combined_data["Date"] = pd.to_datetime(combined_data["Date"])
combined_data.head()

,Index,Description,Duration,Amount,TRPS,Rating,Echelon,Date,Listing,Lombard,Liquidity,EUR,RUB,USD
0,XS2134628069,MMCFN 2.550 09/11/25 '25,4.223,500000000.0,10.0,7,1,2020-12-01,3.0,0,0.342448,0,0,1
1,XS1449458915,GOTRL 5.950 07/19/21,0.558,350000000.0,10.0,5,2,2020-12-01,3.0,1,0.435783,0,0,1
2,XS1319822752,EVRE 8.250 01/28/21,0.097,750000000.0,10.0,6,1,2020-12-01,-1.0,0,0.000000,0,0,1
3,XS1433454243,FASPM 5.375 06/16/23,2.358,900000000.0,10.0,5,2,2020-12-01,3.0,0,0.428966,0,0,1
4,XS1951067039,CBOMF 5.150 02/20/24,2.890,327228000.0,10.0,4,2,2020-12-01,3.0,0,0.439385,1,0,0

In [102]:
df_delete = combined_data[(combined_data['Liquidity']==0)&((combined_data['EUR']==1)|(combined_data['USD']==1))]
# Получаем индексы строк, которые нужно удалить
indices_to_delete = df_delete.index
# Удаляем строки из combined_data
combined_data = combined_data.drop(indices_to_delete)
combined_data = combined_data.reset_index(drop=True)
combined_data.head()

,Index,Description,Duration,Amount,TRPS,Rating,Echelon,Date,Listing,Lombard,Liquidity,EUR,RUB,USD
0,XS2134628069,MMCFN 2.550 09/11/25 '25,4.223,500000000.0,10.0,7,1,2020-12-01,3.0,0,0.342448,0,0,1
1,XS1449458915,GOTRL 5.950 07/19/21,0.558,350000000.0,10.0,5,2,2020-12-01,3.0,1,0.435783,0,0,1
2,XS1433454243,FASPM 5.375 06/16/23,2.358,900000000.0,10.0,5,2,2020-12-01,3.0,0,0.428966,0,0,1
3,XS1951067039,CBOMF 5.150 02/20/24,2.890,327228000.0,10.0,4,2,2020-12-01,3.0,0,0.439385,1,0,0
4,XS2010044381,GTEPT 4.949 02/18/26,4.555,550000000.0,10.0,5,2,2020-12-01,3.0,1,0.499631,0,0,1

In [121]:
df_delete.to_excel('df_delete.xlsx')

In [103]:
X = combined_data[['Duration', 'Amount', 'Rating', 'Listing', 'Liquidity']].values
# X = combined_data[['Duration', 'Amount', 'Rating', 'Listing', 'Lombard', 'Liquidity', 'EUR', 'RUB', 'USD']].values
y = combined_data['Echelon'].values

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.8904109589041096

In [105]:
# Сколько элементов в каждом классе
for i in range(1, 4):
    print(np.count_nonzero(y == i))

396
273
57

<b>Мало элементов из 3 класса, сделаем оверсемплинг</b>

In [106]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority')
X_resampled, y_resampled = smote.fit_resample(X, y)

In [107]:
np.count_nonzero(y_resampled == 1)

396

In [108]:
# Сколько элементов в каждом классе
for i in range(1, 4):
    print(np.count_nonzero(y_resampled == i))

396
273
396

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=30)
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9389671361502347

In [110]:
feature_importances = clf.feature_importances_
feature_importances

array([0.06859813, 0.18361849, 0.57316611, 0.02207913, 0.15253814])

In [111]:
from sklearn.tree import export_text
r = export_text(clf)
print(r)

|--- feature_2 <= 5.50
|   |--- feature_2 <= 3.98
|   |   |--- feature_1 <= 3080002496.00
|   |   |   |--- class: 2
|   |   |--- feature_1 >  3080002496.00
|   |   |   |--- feature_0 <= 7.00
|   |   |   |   |--- feature_0 <= 2.14
|   |   |   |   |   |--- feature_4 <= 0.22
|   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |--- feature_4 >  0.22
|   |   |   |   |   |   |--- feature_0 <= 0.70
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- feature_0 >  0.70
|   |   |   |   |   |   |   |--- feature_4 <= 0.23
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_4 >  0.23
|   |   |   |   |   |   |   |   |--- feature_0 <= 2.06
|   |   |   |   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |   |   |   |--- feature_0 >  2.06
|   |   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |--- feature_0 >  2.14
|   |   |   |   |   |--- class: 3
|   |   |   |--- feature_0 >  7.00
|   |   |   |   |--- class: 2
|   |--- feature_2 >  3.98
|   |   |--- feature_4 <= 0.12
|   |   |   |--- class: 3
|   |   |--- feature_4 >  0.12
|   |   |   |--- feature_4 <= 0.61
|   |   |   |   |--- feature_2 <= 4.31
|   |   |   |   |   |--- class: 2
|   |   |   |   |--- feature_2 >  4.31
|   |   |   |   |   |--- feature_2 <= 4.86
|   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |--- feature_2 >  4.86
|   |   |   |   |   |   |--- feature_1 <= 2450000000.00
|   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- feature_1 >  2450000000.00
|   |   |   |   |   |   |   |--- feature_1 <= 4679293440.00
|   |   |   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |   |   |--- feature_1 >  4679293440.00
|   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |--- feature_4 >  0.61
|   |   |   |   |--- feature_2 <= 4.15
|   |   |   |   |   |--- class: 2
|   |   |   |   |--- feature_2 >  4.15
|   |   |   |   |   |--- class: 3
|--- feature_2 >  5.50
|   |--- feature_2 <= 9.00
|   |   |--- feature_2 <= 7.33
|   |   |   |--- feature_3 <= 1.50
|   |   |   |   |--- feature_0 <= 2.50
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_0 >  2.50
|   |   |   |   |   |--- feature_0 <= 4.77
|   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |--- feature_0 >  4.77
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- feature_3 >  1.50
|   |   |   |   |--- feature_1 <= 3500000000.00
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_1 >  3500000000.00
|   |   |   |   |   |--- feature_1 <= 8500000000.00
|   |   |   |   |   |   |--- feature_0 <= 1.96
|   |   |   |   |   |   |   |--- feature_1 <= 6000000000.00
|   |   |   |   |   |   |   |   |--- feature_0 <= 1.13
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 0.94
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 0.55
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  0.55
|   |   |   |   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |   |   |   |--- feature_0 >  0.94
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_0 >  1.13
|   |   |   |   |   |   |   |   |   |--- feature_2 <= 6.50
|   |   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.28
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_4 >  0.28
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |--- feature_2 >  6.50
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 1.26
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  1.26
|   |   |   |   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |   |--- feature_1 >  6000000000.00
|   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |--- feature_0 >  1.96
|   |   |   |   |   |   |   |--- feature_4 <= 0.52
|   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |   |--- feature_4 >  0.52
|   |   |   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |--- feature_1 >  8500000000.00
|   |   |   |   |   |   |--- feature_0 <= 1.24
|   |   |   |   |   |   |   |--- feature_0 <= 0.44
|   |   |   |   |   |   |   |   |--- feature_0 <= 0.36
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_0 >  0.36
|   |   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |   |--- feature_0 >  0.44
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  1.24
|   |   |   |   |   |   |   |--- feature_4 <= 0.50
|   |   |   |   |   |   |   |   |--- class: 2
|   |   |   |   |   |   |   |--- feature_4 >  0.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |--- feature_2 >  7.33
|   |   |   |--- feature_1 <= 4233405696.00
|   |   |   |   |--- class: 1
|   |   |   |--- feature_1 >  4233405696.00
|   |   |   |   |--- feature_1 <= 14200000512.00
|   |   |   |   |   |--- feature_1 <= 11200000000.00
|   |   |   |   |   |   |--- feature_4 <= 0.36
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_4 >  0.36
|   |   |   |   |   |   |   |--- feature_0 <= 1.50
|   |   |   |   |   |   |   |   |--- feature_4 <= 0.38
|   |   |   |   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |   |   |   |--- feature_4 >  0.38
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.40
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_4 >  0.40
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 1.13
|   |   |   |   |   |   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  1.13
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |--- feature_0 >  1.50
|   |   |   |   |   |   |   |   |--- feature_0 <= 2.78
|   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.42
|   |   |   |   |   |   |   |   |   |   |--- class: 3
|   |   |   |   |   |   |   |   |   |--- feature_4 >  0.42
|   |   |   |   |   |   |   |   |   |   |--- feature_4 <= 0.44
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_4 >  0.44
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |--- feature_0 >  2.78
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_1 >  11200000000.00
|   |   |   |   |   |   |--- class: 2
|   |   |   |   |--- feature_1 >  14200000512.00
|   |   |   |   |   |--- class: 1
|   |--- feature_2 >  9.00
|   |   |--- class: 3

Затест на определенной дате

In [112]:
X = combined_data[combined_data['Date'] == '2022-01-01'][['Duration', 'Amount', 'Rating', 'Listing', 'Liquidity']].values
y = combined_data[combined_data['Date'] == '2022-01-01']['Echelon'].values

In [113]:
y_pred = clf.predict(X)
accuracy = accuracy_score(y, y_pred)
print(accuracy)

0.9454545454545454

In [114]:
for i in range(len(y)):
    print(y[i], y_pred[i])

2 1
1 1
1 1
1 1
1 1
2 2
1 1
2 2
2 2
2 2
1 1
1 1
1 1
1 1
1 1
2 2
1 1
2 2
2 2
1 1
2 2
2 2
2 2
2 2
1 1
2 2
1 1
1 1
3 3
2 2
2 2
2 2
3 3
2 2
1 1
1 1
1 1
1 1
1 1
1 3
1 1
2 2
2 2
1 1
3 3
1 1
2 2
1 1
1 1
2 1
3 3
3 3
2 2
3 3
1 1

In [16]:
combined_data[combined_data['Date'] == '2022-01-01']

,Index,Description,Duration,Amount,TRPS,Rating,Echelon,Date,Listing,Lombard,Liquidity,EUR,RUB,USD
814,RU000A101616,FASPM 5.000 Perp '25,19.322,1.500000e+08,7.0,6,2,2022-01-01,3.0,0,0.456713,1,0,0
815,XS2159874002,LKOH 3.875 05/06/30,7.089,1.500000e+09,10.0,8,1,2022-01-01,3.0,0,0.524221,0,0,1
816,XS2134628069,MMCFN 2.550 09/11/25 '25,3.461,5.000000e+08,10.0,7,1,2022-01-01,3.0,0,0.460428,0,0,1
817,XS2291819980,GAZFI 2.950 01/27/29 MTN,6.252,2.000000e+09,10.0,8,1,2022-01-01,3.0,0,0.482264,0,0,1
818,XS0810596832,VTBR 9.500 Perp '22 FRN,0.853,2.250000e+09,10.0,7,1,2022-01-01,3.0,0,0.636351,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,RU000A102Y58,BRSSD 9.600 04/01/24,1.995,6.000000e+09,7.0,3,3,2022-01-01,3.0,0,0.494870,0,1,0
876,RU000A0JS5R1,VNESH 6.200 03/17/22 PUT,0.153,5.000000e+09,6.0,3,3,2022-01-01,3.0,1,0.000000,0,1,0
877,RU000A0JS603,VNESH 6.250 08/11/22 PUT,0.541,5.000000e+09,8.0,3,2,2022-01-01,3.0,1,0.436158,0,1,0
878,RU000A0JXSF8,TRMK 7.600 05/21/27 PUT,4.420,1.000000e+10,7.0,3,3,2022-01-01,2.0,0,0.437358,0,1,0
879,RU000A102CL3,RUGV 1.850 11/20/32,9.885,1.250000e+09,9.0,7,1,2022-01-01,1.0,0,0.395909,1,0,0

# Запросы по API

In [29]:
import requests
import xml.etree.ElementTree as ET

In [30]:
# Достаем isin облигаций из портфеля
df_isin = pd.read_excel("sec_010724.xlsx")
isin_list = df_isin['ISIN'].tolist()

In [31]:
# Букавы рейтинг меняем на машина понимать язык
replacement_dict = {
    'NR': 0,
    'B-': 1,
    'B': 2,
    'B+': 3,
    'BB-': 4,
    'BB': 5,
    'BB+': 6,
    'BBB-': 7,
    'BBB': 8,
    'BBB+': 9,
    'A-': 10
}
df_isin['Рейтинг'] = df_isin['Рейтинг'].replace(replacement_dict)

In [32]:
set(df_isin['Currency'])

{'AED', 'CNY', 'EUR', 'RUB', 'USD'}

In [34]:
isin_list

['RU000A102CL3',
 'RU000A102CL3',
 'RU000A107D58',
 'RU000A106V57',
 'RU000A1080Z9',
 'RU000A1082Q4',
 'RU000A105104',
 'RU000A105112',
 'RU000A105NH1',
 'RU000A108Q29',
 'XS2120091991',
 'RU000A102K96',
 'RU000A105KU0',
 'RU000A107AQ5',
 'RU000A107B43',
 'RU000A107CX7',
 'RU000A105EV1',
 'RU000A1059R0',
 'RU000A105M75',
 'RU000A1086M4',
 'RU000A107VV1',
 'XS2281299763',
 'RU000A107AB7',
 'RU000A1057S2',
 'RU000A101616',
 'RU000A106V57',
 'RU000A105104',
 'RU000A105112',
 'XS2010040397',
 'RU000A107JY0',
 'RU000A1086Z6',
 'RU000A103R80',
 'RU000A107X96',
 'RU000A107AU7',
 'RU000A106LL5',
 'RU000A108KT6',
 'RU000A108P46',
 'RU000A106EM8',
 'RU000A105WC3',
 'RU000A105XE7',
 'RU000A105X80',
 'RU000A107605',
 'RU000A107HH9',
 'RU000A107UX9',
 'RU000A107050',
 'RU000A107084',
 'RU000A107ET1',
 'RU000A108JV4',
 'RU000A0ZYR91',
 'RU000A105KW6',
 'RU000A1064L3',
 'RU000A107EA1',
 'RU000A106F40',
 'RU000A107DS5',
 'RU000A108Q03',
 'RU000A1078S8',
 'RU000A107456',
 'RU000A1083A6',
 'RU000A101780',
 'RU000A101T56',
 'RU000A101UE2',
 'RU000A1077V4',
 'RU000A107RZ0',
 'RU000A104JQ3',
 'RU000A1053P7',
 'RU000A105SP3',
 'RU000A106Z46',
 'RU000A107SM6',
 'RU000A108GL1',
 'RU000A1008J4',
 'RU000A105L27',
 'RU000A107GX8',
 'RU000A107TK8',
 'RU000A103QH9',
 'RU000A0ZZ1J8',
 'RU000A103JR3',
 'RU000A1008V9',
 'RU000A0JWV63',
 'RU000A1056S4',
 'RU000A1023K1',
 'RU000A0JS3W6',
 'RU000A0JVW48',
 'RU000A0ZYUA9',
 'RU000A1038Z7',
 'RU000A105RV3',
 'RU000A106E90',
 'RU000A0JTK38',
 'RU000A0ZYUB7',
 'RU000A0ZZYW2',
 'RU000A100A82',
 'RU000A100EF5',
 'RU000A103BR0',
 'RU000A0JV4M0',
 'RU000A0JXQF2',
 'RU000A100EG3',
 'RU000A1014N4',
 'RU000A101QE0',
 'RU000A106EM8',
 'RU000A107456',
 'RU000A107DS5',
 'RU000A104YT6',
 'RU000A105KU0',
 'RU000A105RG4',
 'RU000A105R62',
 'RU000A0JWZY6',
 'RU000A0JVA10',
 'RU000A0JX1S1',
 'RU000A101137',
 'RU000A102DB2',
 'RU000A100VQ6',
 'RU000A0JS3W6',
 'RU000A0JTK38',
 'RU000A100A82',
 'RU000A102CR0']

In [35]:
def currency_exc(date_from, date_till):
    data = []
    
    # Словарь с кодами валют
    currency_codes = {
        'USD': 'R01235',
        'EUR': 'R01239',
        'AED': 'R01230',
        'CNY': 'R01375'
        # Добавьте другие валюты по необходимости
    }
    
    # Преобразование строк с датами в формат 'dd/mm/yyyy'
    date_from_str = datetime.strptime(date_from, '%Y-%m-%d').strftime('%d/%m/%Y')
    date_till_str = datetime.strptime(date_till, '%Y-%m-%d').strftime('%d/%m/%Y')
    
    for char_code, iso_code in currency_codes.items():
        # Формирование URL для запроса
        url = f'https://www.cbr.ru/scripts/XML_dynamic.asp?date_req1={date_from_str}&date_req2={date_till_str}&VAL_NM_RQ={iso_code}'

        # Запрос данных
        response = requests.get(url)
        if response.status_code != 200:
            print(f"Ошибка при запросе данных для {char_code}: {response.status_code}")
            continue

        # Парсинг XML-ответа
        root = ET.fromstring(response.content)
        for record in root.findall('Record'):
            date = record.attrib['Date']
            value = record.find('Value').text
            nominal = int(record.find('Nominal').text)
            rate = float(value.replace(',', '.')) / nominal
            data.append({
                'Date': datetime.strptime(date, '%d.%m.%Y').date(),
                'Currency': char_code,
                'Rate': rate
            })

    # Создание DataFrame
    df = pd.DataFrame(data)

    # Заполнение пропущенных дат
    date_from_obj = datetime.strptime(date_from, '%Y-%m-%d').date()
    date_till_obj = datetime.strptime(date_till, '%Y-%m-%d').date()
    all_dates = pd.date_range(start=date_from_obj, end=date_till_obj)

    full_df = pd.DataFrame()

    for currency in currency_codes.keys():
        currency_df = df[df['Currency'] == currency]
        currency_df = currency_df.set_index('Date').reindex(all_dates).fillna(method='ffill').reset_index()
        currency_df['Currency'] = currency
        full_df = pd.concat([full_df, currency_df])

    # Переименование столбцов после объединения
    full_df.columns = ['Date', 'Currency', 'Rate']
    full_df = full_df[['Date', 'Currency', 'Rate']]

    # Преобразование столбца 'Date' в тип datetime.date
    full_df['Date'] = full_df['Date'].apply(lambda x: x.date())

    return full_df

In [36]:
# Создаем датафрейм курсов валют по датам
date_from = '2024-05-17'
date_till = '2024-06-30'
df_currency = currency_exc(date_from, date_till)

In [37]:
df_currency.head()

         Date Currency     Rate
0  2024-05-17      USD  90.9239
1  2024-05-18      USD  90.9873
2  2024-05-19      USD  90.9873
3  2024-05-20      USD  90.9873
4  2024-05-21      USD  90.6537

## Подсчет среднего объема и кол-ва сделок для каждой бумаги

In [134]:
value_list = []
num_trades_list = []
listing_list = []

for isin in isin_list:
    # isin = 'RU000A102CL3'
    print(isin)
    url_isin = f'https://iss.moex.com/iss/securities?q={isin}&securities.columns=secid'
    # Отправка GET-запроса чтобы вытащить secid
    response_isin = requests.get(url_isin)
    try:
        if response_isin.status_code == 200:
            data_secid = pd.read_xml(response_isin.content, xpath=".//rows/row")
            secid = data_secid.iloc[0]['secid']
            isin = secid
            print(isin)
        else:
            print(f"Ошибка при доступе к API MOEX: {url_isin}")
    except:
        print(f'Нет secid для isin')
    # URL для получения данных по облигациям, котируемым на MOEX
    url = f'https://iss.moex.com/iss/history/engines/stock/markets/bonds/securities/{isin}?from={date_from}&till={date_till}&sort_order=desc&iss.only=history'
    url_listing = f'https://iss.moex.com/iss/engines/stock/markets/bonds/securities/{isin}?securities.columns=SECID,LISTLEVEL&iss.only=securities&iss.only=history'
    # Отправка GET-запроса к API MOEX
    response = requests.get(url)
    # Переменные для сумм объемов
    value_sum = 0
    num_trades_sum = 0
    try:
        # Проверка статуса ответа
        if response.status_code == 200:
            # Парсинг XML
            df = pd.read_xml(response.content, xpath=".//rows/row") 
            df = df[['TRADEDATE', 'BOARDID', 'VALUE', 'VOLUME', 'WAPRICE', 'FACEUNIT', 'CURRENCYID', 'FACEVALUE', 'NUMTRADES']]

            # Подсчет количества торговых дней
            days = df['TRADEDATE'].nunique()

            # Удаляются все строки, в столбце 'VALUE' которых значения равны 0 либо Nan
            mask = ((df['VALUE'] == 0) | df['VALUE'].isna())
            df = df[~mask]

            # Пробегаемся по строкам, складываем VALUE*валюта расчета
            for index, row in df.iterrows():
                # курс валюты строки к рублю
                date = datetime.strptime(row['TRADEDATE'], '%Y-%m-%d').date()

                if row['CURRENCYID'] == 'SUR' or row['CURRENCYID'] == 'RUR' or row['CURRENCYID'] == 'RUB':
                    currency = 1
                else:
                    # ищем строку с курсом
                    result = df_currency.loc[(df_currency['Date'] == date) & (df_currency['Currency'] == row['CURRENCYID'])]
                    if not result.empty:
                        currency = result.iloc[0]['Rate']
#                         print(f"\nКурс {row['CURRENCYID']} на {date}: {currency}")
                    else:
                        print(f"\nЗапись не найдена {row['CURRENCYID']} на {date}")

                # умножаем объем на курс
                value_row = row['VALUE'] * currency
                value_sum += value_row
                num_trades_sum += row['NUMTRADES']

            value_list.append(value_sum/days)
            num_trades_list.append(num_trades_sum/days)
        else:
            print(f"Ошибка при доступе к API MOEX: {url}")
    except:
        value_list.append(0)
        num_trades_list.append(0)
        print(f"Нет данных торгов для ISIN: {isin}")

    # Отправка GET-запроса к API MOEX
    response_listing = requests.get(url_listing)

    try:
        # Проверка статуса ответа
        if response_listing.status_code == 200:
            # Парсинг XML
            data_listing = pd.read_xml(response_listing.content, xpath=".//rows/row")
            listing_rank = data_listing.iloc[0]['LISTLEVEL']
            listing_list.append(listing_rank)
            print(listing_rank)
        else:
            print(f"Ошибка при доступе к API MOEX: {url_listing}")
    except:
        listing_rank = -1
        listing_list.append(listing_rank)
        print(f"Нет данных листинга для ISIN: {isin}")

RU000A102CL3
RU000A102CL3
1.0
RU000A102CL3
RU000A102CL3
1.0
RU000A107D58
RU000A107D58
3.0
RU000A106V57
RU000A106V57
2.0
RU000A1080Z9
RU000A1080Z9
3.0
RU000A1082Q4
RU000A1082Q4
3.0
RU000A105104
RU000A105104
3.0
RU000A105112
RU000A105112
3.0
RU000A105NH1
RU000A105NH1
3.0
RU000A108Q29
RU000A108Q29
3.0
XS2120091991
XS2120091991
Нет данных торгов для ISIN: XS2120091991
Нет данных листинга для ISIN: XS2120091991
RU000A102K96
RU000A102K96
1.0
RU000A105KU0
RU000A105KU0
3.0
RU000A107AQ5
RU000A107AQ5
3.0
RU000A107B43
RU000A107B43
3.0
RU000A107CX7
RU000A107CX7
3.0
RU000A105EV1
RU000A105EV1
1.0
RU000A1059R0
RU000A1059R0
3.0
RU000A105M75
RU000A105M75
3.0
RU000A1086M4
RU000A1086M4
3.0
RU000A107VV1
RU000A107VV1
3.0
XS2281299763
XS2281299763
Нет данных торгов для ISIN: XS2281299763
Нет данных листинга для ISIN: XS2281299763
RU000A107AB7
Нет secid для isin
Нет данных торгов для ISIN: RU000A107AB7
Нет данных листинга для ISIN: RU000A107AB7
RU000A1057S2
RU000A1057S2
3.0
RU000A101616
RU000A101616
3.0
RU000A106V57
RU000A106V57
2.0
RU000A105104
RU000A105104
3.0
RU000A105112
RU000A105112
3.0
XS2010040397
XS2010040397
3.0
RU000A107JY0
RU000A107JY0
3.0
RU000A1086Z6
RU000A1086Z6
Нет данных торгов для ISIN: RU000A1086Z6
Нет данных листинга для ISIN: RU000A1086Z6
RU000A103R80
RU000A103R80
Нет данных торгов для ISIN: RU000A103R80
Нет данных листинга для ISIN: RU000A103R80
RU000A107X96
RU000A107X96
3.0
RU000A107AU7
RU000A107AU7
3.0
RU000A106LL5
RU000A106LL5
3.0
RU000A108KT6
RU000A108KT6
3.0
RU000A108P46
RU000A108P46
2.0
RU000A106EM8
RU000A106EM8
2.0
RU000A105WC3
RU000A105WC3
3.0
RU000A105XE7
RU000A105XE7
3.0
RU000A105X80
RU000A105X80
3.0
RU000A107605
RU000A107605
3.0
RU000A107HH9
RU000A107HH9
3.0
RU000A107UX9
RU000A107UX9
3.0
RU000A107050
RU000A107050
2.0
RU000A107084
RU000A107084
2.0
RU000A107ET1
RU000A107ET1
2.0
RU000A108JV4
RU000A108JV4
2.0
RU000A0ZYR91
RU000A0ZYR91
1.0
RU000A105KW6
RU000A105KW6
1.0
RU000A1064L3
RU000A1064L3
1.0
RU000A107EA1
RU000A107EA1
1.0
RU000A106F40
RU000A106F40
1.0
RU000A107DS5
RU000A107DS5
3.0
RU000A108Q03
RU000A108Q03
3.0
RU000A1078S8
RU000A1078S8
1.0
RU000A107456
RU000A107456
3.0
RU000A1083A6
RU000A1083A6
2.0
RU000A101780
RU000A101780
2.0
RU000A101T56
RU000A101T56
2.0
RU000A101UE2
RU000A101UE2
2.0
RU000A1077V4
RU000A1077V4
3.0
RU000A107RZ0
RU000A107RZ0
1.0
RU000A104JQ3
RU000A104JQ3
1.0
RU000A1053P7
RU000A1053P7
3.0
RU000A105SP3
RU000A105SP3
3.0
RU000A106Z46
RU000A106Z46
1.0
RU000A107SM6
RU000A107SM6
1.0
RU000A108GL1
RU000A108GL1
1.0
RU000A1008J4
RU000A1008J4
1.0
RU000A105L27
RU000A105L27
1.0
RU000A107GX8
RU000A107GX8
1.0
RU000A107TK8
RU000A107TK8
1.0
RU000A103QH9
RU000A103QH9
2.0
RU000A0ZZ1J8
RU000A0ZZ1J8
1.0
RU000A103JR3
RU000A103JR3
2.0
RU000A1008V9
RU000A1008V9
3.0
RU000A0JWV63
RU000A0JWV63
3.0
RU000A1056S4
RU000A1056S4
2.0
RU000A1023K1
RU000A1023K1
1.0
RU000A0JS3W6
SU26207RMFS9
1.0
RU000A0JVW48
SU26218RMFS6
1.0
RU000A0ZYUA9
SU26224RMFS4
1.0
RU000A1038Z7
SU26237RMFS6
1.0
RU000A105RV3
SU26242RMFS6
1.0
RU000A106E90
SU26243RMFS4
1.0
RU000A0JTK38
SU26212RMFS9
1.0
RU000A0ZYUB7
SU26225RMFS1
1.0
RU000A0ZZYW2
SU26226RMFS9
1.0
RU000A100A82
SU26228RMFS5
1.0
RU000A100EF5
SU26230RMFS1
1.0
RU000A103BR0
SU26240RMFS0
1.0
RU000A0JV4M0
SU29007RMFS0
1.0
RU000A0JXQF2
SU26222RMFS8
1.0
RU000A100EG3
SU26229RMFS3
1.0
RU000A1014N4
SU26232RMFS7
1.0
RU000A101QE0
SU26234RMFS3
1.0
RU000A106EM8
RU000A106EM8
2.0
RU000A107456
RU000A107456
3.0
RU000A107DS5
RU000A107DS5
3.0
RU000A104YT6
RU000A104YT6
1.0
RU000A105KU0
RU000A105KU0
3.0
RU000A105RG4
RU000A105RG4
3.0
RU000A105R62
RU000A105R62
3.0
RU000A0JWZY6
RU000A0JWZY6
1.0
RU000A0JVA10
RU000A0JVA10
1.0
RU000A0JX1S1
RU000A0JX1S1
3.0
RU000A101137
RU000A101137
3.0
RU000A102DB2
RU000A102DB2
1.0
RU000A100VQ6
RU000A100VQ6
2.0
RU000A0JS3W6
SU26207RMFS9
1.0
RU000A0JTK38
SU26212RMFS9
1.0
RU000A100A82
SU26228RMFS5
1.0
RU000A102CR0
RU000A102CR0
1.0

In [135]:
df_isin['Value_avg'] = value_list
df_isin['Num_trades_avg'] = num_trades_list
df_isin['Listing'] = listing_list

In [136]:
df_isin.head()

,ISIN,Duration,Currency,Рейтинг,Amount Outstanding,Value_avg,Num_trades_avg,Listing
0,RU000A102CL3,7.146329,EUR,7,1250000000,3.064499e+06,0.4,1.0
1,RU000A102CL3,7.146329,EUR,7,1250000000,3.064499e+06,0.4,1.0
2,RU000A107D58,3.830634,USD,5,141112000,1.254337e+07,35.0,3.0
3,RU000A106V57,1.065374,AED,5,370000000,1.048308e+05,2.1,2.0
4,RU000A1080Z9,1.402525,CNY,3,160944000,5.863805e+06,164.5,3.0

## Подсчет среднедневного объема и кол-ва сделок по всем инструментам

In [42]:
# Создаем список дат между from и till
date_list = pd.date_range(start=date_from, end=date_till).strftime('%Y-%m-%d').tolist()
# Создаем список интересующих режимов торгов
boards_list = ['TQCB', 'TQOE', 'TQOD', 'TQOY']

In [44]:
# date = date_list[0]
# board = boards_list[2]
num_trades_all_list = []
value_all_list = []
for date in date_list:
    for board in boards_list:
        # Базовый URL для запроса
        base_url = f'https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/{board}/securities.xml'

        params = {
            'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID',
            'iss.only': 'history',
            'date': date,
            'start': 0
        }

        # Читаем 1 дату
        val_sum_day = 0
        num_trades_day = 0
        while True:
            # Отправка GET-запроса к API MOEX
            response = requests.get(base_url, params=params)

            # Проверка статуса ответа
            if response.status_code == 200:
                try:
                    # Парсинг XML
                    df = pd.read_xml(response.content, xpath=".//rows/row")

                    if df.empty:
                        break  # Если данных больше нет, прекращаем запросы

                    # Удаляются все строки, в столбце 'VALUE' которых значения равны 0 либо Nan
                    mask = ((df['VALUE'] == 0) | df['VALUE'].isna())
                    df = df[~mask]

                    # Пробегаемся по строкам, складываем VALUE*валюта расчета
                    for index, row in df.iterrows():
                        # курс валюты строки к рублю
                        date_cur = datetime.strptime(date, '%Y-%m-%d').date()

                        if row['CURRENCYID'] == 'SUR' or row['CURRENCYID'] == 'RUR' or row['CURRENCYID'] == 'RUB':
                            currency = 1
                        else:
                            # ищем строку с курсом
                            result = df_currency.loc[(df_currency['Date'] == date_cur) & (df_currency['Currency'] == row['CURRENCYID'])]
                            if not result.empty:
                                currency = result.iloc[0]['Rate']
                            else:
                                print(f"\nЗапись не найдена {row['CURRENCYID']} на {date_cur}")

                        # умножаем объем на курс
                        value_row = row['VALUE'] * currency
                        val_sum_day += value_row

                    num_trades_day += sum(df['NUMTRADES'])

                    # Увеличиваем смещение для следующего запроса
                    params['start'] += 100

                    # Задержка для предотвращения слишком частых запросов
                    sleep(0.5)
                except:
                    if params['start'] > 0:
                        print('Парсинг закончен')
                    else: 
                        print(f'Нет никаких данных по ссылке: {base_url}, {params}')
                    break
            else:
                print(f"Ошибка при доступе к API MOEX: {base_url}, {params}")
                break

        value_all_list.append(val_sum_day)
        num_trades_all_list.append(num_trades_day)

Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-18', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-18', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-18', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-18', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-19', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-19', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-19', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-19', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-25', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-25', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-25', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-25', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-26', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-26', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-26', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-05-26', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-01', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-01', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-01', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-01', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-02', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-02', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-02', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-02', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-08', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-08', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-08', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-08', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-09', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-09', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-09', 'start': 0}

Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-09', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-12', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-12', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-12', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-12', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-15', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-15', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-15', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-15', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-16', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-16', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-16', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-16', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-22', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-22', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-22', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-22', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-23', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-23', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-23', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-23', 'start': 0}
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Парсинг закончен
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-29', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-29', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-29', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-29', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQCB/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-30', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOE/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-30', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOD/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-30', 'start': 0}
Нет никаких данных по ссылке: https://iss.moex.com/iss/history/engines/stock/markets/bonds/boards/TQOY/securities.xml, {'history.columns': 'SECID,NUMTRADES,VALUE,CURRENCYID', 'iss.only': 'history', 'date': '2024-06-30', 'start': 0}

In [45]:
num_trades_all_list

[101233,
 2,
 180,
 1017,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 120156,
 3,
 161,
 1833,
 121670,
 0,
 186,
 1912,
 124544,
 2,
 163,
 1736,
 116901,
 0,
 200,
 1516,
 121819,
 1,
 148,
 3087,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 156184,
 0,
 267,
 4596,
 126859,
 0,
 203,
 1806,
 104473,
 0,
 209,
 1747,
 99716,
 1,
 133,
 1991,
 125457,
 0,
 150,
 3600,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 155686,
 1,
 212,
 1625,
 115340,
 3,
 140,
 2098,
 105005,
 5,
 214,
 1196,
 94089,
 0,
 208,
 1248,
 111147,
 0,
 215,
 1101,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 122896,
 0,
 141,
 1665,
 107701,
 0,
 182,
 1507,
 0,
 0,
 0,
 0,
 128644,
 0,
 0,
 4096,
 119036,
 0,
 0,
 2010,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 143490,
 0,
 0,
 2433,
 121899,
 0,
 0,
 4999,
 134829,
 0,
 0,
 4417,
 117631,
 0,
 0,
 4570,
 102246,
 0,
 0,
 2887,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 105436,
 0,
 0,
 2600,
 112378,
 0,
 0,
 1610,
 104771,
 0,
 0,
 2374,
 105032,
 0,
 0,
 2325,
 108274,
 0,
 0,
 2444,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

### Итак, среднедневной объем и кол-ва сделок по всем инструментам равно:

In [137]:
# Cреднедневной объем
value_all_avg = sum(value_all_list)/30
# Среднедневное кол-во сделок
num_trades_all_avg = sum(num_trades_all_list)/30
print(f'Cреднедневной объем c {date_from} по {date_till}: {value_all_avg}')
print(f'Cреднедневное кол-во сделок c {date_from} по {date_till}: {num_trades_all_avg}')

Cреднедневной объем c 2024-05-17 по 2024-06-30: 8340786004.126866
Cреднедневное кол-во сделок c 2024-05-17 по 2024-06-30: 120330.6

In [47]:
df_isin.head(3)

,ISIN,Duration,Currency,Рейтинг,Amount Outstanding,Value_avg,Num_trades_avg,Listing
0,RU000A102CL3,7.146329,EUR,7,1250000000,3.064499e+06,0.4,1.0
1,RU000A102CL3,7.146329,EUR,7,1250000000,3.064499e+06,0.4,1.0
2,RU000A107D58,3.830634,USD,5,141112000,1.254337e+07,35.0,3.0

## Рассчитываем ликвидность

In [138]:
liquidity_list = []
# Коэффициенты из формулы
a = 0.03
b = 0.07
for index, row in df_isin.iterrows():
    liquidity_row = ((row['Value_avg']/value_all_avg)**a) * ((row['Num_trades_avg']/num_trades_all_avg)**b)
    liquidity_list.append(liquidity_row)

In [139]:
df_final = pd.DataFrame()
df_final['ISIN'] = df_isin['ISIN']
df_final['Duration'] = df_isin['Duration'] 
df_final['Amount'] = df_isin['Amount Outstanding'] 
df_final['Rating'] = df_isin['Рейтинг'] 
df_final['Listing'] = df_isin['Listing'] 
df_final['Liquidity'] = liquidity_list 
df_final['Currency'] = df_isin['Currency']

In [140]:
df_final.head()

           ISIN  Duration      Amount  Rating  Listing  Liquidity Currency
0  RU000A102CL3  7.146329  1250000000       7      1.0   0.326191      EUR
1  RU000A102CL3  7.146329  1250000000       7      1.0   0.326191      EUR
2  RU000A107D58  3.830634   141112000       5      3.0   0.465345      USD
3  RU000A106V57  1.065374   370000000       5      2.0   0.331061      AED
4  RU000A1080Z9  1.402525   160944000       3      3.0   0.506891      CNY

In [141]:
X = df_final[['Duration', 'Amount', 'Rating', 'Listing', 'Liquidity']].values
y_pred = clf.predict(X)
print(y_pred)

[1 1 2 2 2 1 2 2 1 1 2 1 1 2 2 2 1 1 1 2 2 3 2 1 1 2 2 2 3 2 1 1 1 1 1 2 3
 2 2 2 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 2 1 2 1 3 2 3 2 2 2 2 2 2 2 1 2
 2 2 2 2 2 2 1 2 2 2 2 1 2 1 1 2 1 1 1 1 1 2 1 2 2 1 2 1 1 1 2 2 2 1 1 1 1
 2 2 1]

In [142]:
# Добавляем предсказанные значения в DataFrame
df_final['Echelon predicted'] = y_pred

# Итерируемся по строкам DataFrame и изменяем значения
for index, row in df_final.iterrows():
    if (row['Liquidity'] == 0) & ((row['Currency'] == 'EUR') | (row['Currency'] == 'USD')):
        df_final.loc[index, 'Echelon predicted'] = 3

# Сохраняем DataFrame в Excel
df_final.to_excel('Эшелоны_предикт.xlsx', index=False)

In [143]:
df_final

,ISIN,Duration,Amount,Rating,Listing,Liquidity,Currency,Echelon predicted
0,RU000A102CL3,7.146329,1250000000,7,1.0,0.326191,EUR,1
1,RU000A102CL3,7.146329,1250000000,7,1.0,0.326191,EUR,1
2,RU000A107D58,3.830634,141112000,5,3.0,0.465345,USD,2
3,RU000A106V57,1.065374,370000000,5,2.0,0.331061,AED,2
4,RU000A1080Z9,1.402525,160944000,3,3.0,0.506891,CNY,2
...,...,...,...,...,...,...,...,...
109,RU000A100VQ6,0.205482,25000000000,7,2.0,0.510202,RUB,1
110,RU000A0JS3W6,1.972521,371813713000,7,1.0,0.665371,RUB,1
111,RU000A0JTK38,2.619608,350000000000,7,1.0,0.618086,RUB,2
112,RU000A100A82,3.881491,450000000000,7,1.0,0.585404,RUB,2
113,RU000A102CR0,1.050833,21000000000,7,1.0,0.414922,RUB,1